CREATE TABLE "android_devices" (
	"id" serial PRIMARY KEY NOT NULL,
	"node_code" text NOT NULL,
	"device_name" text NOT NULL,
	"manufacturer" text NOT NULL,
	"model_code" text NOT NULL,
	"android_version" text NOT NULL,
	"soc_chipset" text NOT NULL,
	"ram_gb" integer DEFAULT 12 NOT NULL,
	"resolution" text DEFAULT '1440x3120 @ 480dpi' NOT NULL,
	"imei" text NOT NULL,
	"android_id" text NOT NULL,
	"mac_address" text NOT NULL,
	"build_fingerprint" text NOT NULL,
	"status" text DEFAULT 'ONLINE' NOT NULL,
	"active_app" text DEFAULT 'HOME' NOT NULL,
	"cpu_usage" integer DEFAULT 24 NOT NULL,
	"ram_usage_mb" integer DEFAULT 3200 NOT NULL,
	"battery_level" integer DEFAULT 88 NOT NULL,
	"fps" integer DEFAULT 60 NOT NULL,
	"cluster_shard" text DEFAULT 'SHARD-01' NOT NULL,
	"proxy_protocol" text DEFAULT 'SOCKS5' NOT NULL,
	"proxy_ip" text NOT NULL,
	"proxy_port" integer DEFAULT 1080 NOT NULL,
	"proxy_username" text NOT NULL,
	"proxy_password" text NOT NULL,
	"proxy_country" text NOT NULL,
	"proxy_country_code" text NOT NULL,
	"proxy_city" text NOT NULL,
	"proxy_isp" text NOT NULL,
	"proxy_asn" text NOT NULL,
	"proxy_latency_ms" integer DEFAULT 28 NOT NULL,
	"webrtc_shield" boolean DEFAULT true NOT NULL,
	"dns_leak_protection" boolean DEFAULT true NOT NULL,
	"gmail_address" text NOT NULL,
	"gmail_password" text NOT NULL,
	"gmail_recovery" text NOT NULL,
	"gmail_status" text DEFAULT 'VERIFIED_2FA' NOT NULL,
	"gmail_unread_count" integer DEFAULT 3 NOT NULL,
	"fb_name" text NOT NULL,
	"fb_email" text NOT NULL,
	"fb_uid" text NOT NULL,
	"fb_password" text NOT NULL,
	"fb_2fa_secret" text NOT NULL,
	"fb_status" text DEFAULT 'ADS_READY' NOT NULL,
	"fb_friends_count" integer DEFAULT 640 NOT NULL,
	"yt_channel_name" text NOT NULL,
	"yt_handle" text NOT NULL,
	"yt_subscribers" integer DEFAULT 1250 NOT NULL,
	"yt_watch_hours" integer DEFAULT 340 NOT NULL,
	"yt_status" text DEFAULT 'VERIFIED_CHANNEL' NOT NULL,
	"cookie_token_digest" text NOT NULL,
	"last_synced_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "android_devices_node_code_unique" UNIQUE("node_code"),
	CONSTRAINT "android_devices_imei_unique" UNIQUE("imei"),
	CONSTRAINT "android_devices_android_id_unique" UNIQUE("android_id"),
	CONSTRAINT "android_devices_proxy_ip_unique" UNIQUE("proxy_ip")
);
--> statement-breakpoint
CREATE TABLE "automation_tasks" (
	"id" serial PRIMARY KEY NOT NULL,
	"task_name" text NOT NULL,
	"target_scope" text NOT NULL,
	"app_target" text NOT NULL,
	"devices_affected" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'COMPLETED' NOT NULL,
	"command_script" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_node_code" ON "android_devices" USING btree ("node_code");--> statement-breakpoint
CREATE INDEX "idx_cluster_shard" ON "android_devices" USING btree ("cluster_shard");--> statement-breakpoint
CREATE INDEX "idx_status" ON "android_devices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_proxy_country" ON "android_devices" USING btree ("proxy_country_code");--> statement-breakpoint
CREATE INDEX "idx_manufacturer" ON "android_devices" USING btree ("manufacturer");